//! DNS slice schema (ADR-0005 §3.1).
//!
//! [`crate::config_slices::render_dns`] renders this into the sing-box 1.12+
//! type-based DNS format (each `dns.servers` entry carries `type`).

use serde::{Deserialize, Serialize};

use super::default_true;

/// DNS slice: structured form of the sing-box top-level `dns` object.
///
/// All fields are `#[serde(default)]` for forward compatibility; a missing or
/// partial object deserializes to sensible defaults (slice disabled).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct DnsSlice {
    /// Slice master switch; `false` never injects the DNS slice.
    #[serde(default)]
    pub enabled: bool,
    /// Platform DNS mode (only Android diverges; desktop always behaves as takeover).
    #[serde(default)]
    pub mode: DnsMode,
    /// DNS servers (curated fields).
    #[serde(default)]
    pub servers: Vec<DnsServer>,
    /// DNS routing rules (curated fields).
    #[serde(default)]
    pub rules: Vec<DnsRule>,
    /// Default server tag (sing-box `dns.final`); required when takeover is on.
    #[serde(default)]
    pub final_tag: String,
    /// Default domain strategy (sing-box `dns.strategy`).
    #[serde(default)]
    pub strategy: DnsStrategy,
}

/// Platform DNS mode (ADR-0005 D1).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DnsMode {
    /// Follow the system resolver: Android keeps `inject_android_dns`, so the
    /// slice DNS body does not take effect.
    #[default]
    FollowSystem,
    /// Take over DNS: `inject_android_dns` is skipped and the slice body applies.
    Takeover,
}

/// Domain resolution strategy (maps to sing-box `strategy` / `domain_strategy`).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DnsStrategy {
    #[default]
    PreferIpv4,
    PreferIpv6,
    Ipv4Only,
    Ipv6Only,
}

impl DnsStrategy {
    /// sing-box wire value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::PreferIpv4 => "prefer_ipv4",
            Self::PreferIpv6 => "prefer_ipv6",
            Self::Ipv4Only => "ipv4_only",
            Self::Ipv6Only => "ipv6_only",
        }
    }
}

/// A single DNS server (curated fields).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct DnsServer {
    /// Unique tag within the slice; referenced by `dns.rules` and `dns.final`.
    #[serde(default)]
    pub tag: String,
    /// Server address (IP or domain); unused for [`DnsServerType::Local`].
    #[serde(default)]
    pub server: String,
    /// Server type (`udp` / `tls` / `https` / `quic` / `h3` / `local`).
    #[serde(default)]
    pub server_type: DnsServerType,
    /// Server port (sing-box default per type when omitted).
    #[serde(default)]
    pub server_port: Option<u16>,
    /// Dial field: upstream outbound tag (empty = default direct dial).
    #[serde(default)]
    pub detour: String,
    /// Per-server strategy override.
    ///
    /// **Not rendered**: sing-box 1.12+ new DNS servers have no per-server query
    /// strategy field (the old `strategy` server field was removed). The top-level
    /// [`DnsSlice::strategy`] and DNS rule actions cover this instead; the field
    /// is kept for schema completeness / future use.
    #[serde(default)]
    pub strategy: Option<DnsStrategy>,
    /// Dial field: DNS server tag used to resolve this server's own domain.
    #[serde(default)]
    pub domain_resolver: String,
}

/// DNS server type (`dns.servers[].type`).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DnsServerType {
    #[default]
    Udp,
    Tls,
    Https,
    Quic,
    H3,
    /// System resolver; rendered without `server` / `server_port`.
    Local,
}

impl DnsServerType {
    /// sing-box wire value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Udp => "udp",
            Self::Tls => "tls",
            Self::Https => "https",
            Self::Quic => "quic",
            Self::H3 => "h3",
            Self::Local => "local",
        }
    }

    /// Whether this type dials a `server` address.
    #[must_use]
    pub const fn uses_server(self) -> bool {
        !matches!(self, Self::Local)
    }
}

/// A single DNS routing rule (rendered to `dns.rules[]`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DnsRule {
    /// Unique rule ID (UUID v4 generated by the frontend).
    #[serde(default)]
    pub id: String,
    /// Whether the rule is active.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Match type (determines the sing-box match field).
    #[serde(default)]
    pub match_type: DnsMatchType,
    /// Match target (semantics depend on `match_type`).
    #[serde(default)]
    pub target: String,
    /// Target DNS server tag (`action: "route"`).
    #[serde(default)]
    pub server_tag: String,
}

/// DNS rule match type.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DnsMatchType {
    #[default]
    Domain,
    DomainSuffix,
    DomainKeyword,
    RuleSet,
}

impl DnsMatchType {
    /// sing-box match field name for this match type.
    #[must_use]
    pub const fn field(self) -> &'static str {
        match self {
            Self::Domain => "domain",
            Self::DomainSuffix => "domain_suffix",
            Self::DomainKeyword => "domain_keyword",
            Self::RuleSet => "rule_set",
        }
    }
}
