//! Custom outbound slice schema (ADR-0005 §3.1).
//!
//! Each protocol struct only carries curated high-value fields; everything else
//! stays available through the YAML/JS override escape hatch (ADR-0005 D2).
//! Rendering lives in [`crate::config_slices::render_outbound`].

use serde::{Deserialize, Serialize};

use super::default_true;

/// Forced prefix for every slice-managed outbound tag (ADR-0005 §3.1).
pub const OUTBOUND_TAG_PREFIX: &str = "slice-";

/// Custom outbound slice.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutboundsSlice {
    /// Slice master switch; `false` never injects custom outbounds.
    #[serde(default)]
    pub enabled: bool,
    /// User-defined outbounds.
    #[serde(default)]
    pub items: Vec<CustomOutbound>,
}

/// A single custom outbound. `protocol` is a tagged enum flattened into the
/// object, so the stored JSON is `{ id, name, enabled, type, …protocol fields }`.
///
/// Every field is `#[serde(default)]` except the flattened `protocol`, whose
/// `type` discriminator is inherently required; an item without a known `type`
/// makes the file fail to parse, so [`crate::config_slices::ConfigSlicesStore::load`]
/// falls back to the default (empty) slice set.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustomOutbound {
    /// Unique ID (UUID v4 generated by the frontend).
    #[serde(default)]
    pub id: String,
    /// Display name; also the source of the generated `slice-` tag.
    #[serde(default)]
    pub name: String,
    /// Whether the outbound is injected.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Protocol-specific fields (structured enum, tagged by `type`).
    #[serde(flatten)]
    pub protocol: OutboundProtocol,
}

impl CustomOutbound {
    /// Resolved sing-box outbound tag (`slice-` + slug of [`Self::name`]).
    #[must_use]
    pub fn tag(&self) -> String {
        outbound_tag(&self.name)
    }
}

/// Protocol-specific outbound payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OutboundProtocol {
    Vless(VlessOutbound),
    Vmess(VmessOutbound),
    Shadowsocks(ShadowsocksOutbound),
    Trojan(TrojanOutbound),
    Hysteria2(Hysteria2Outbound),
}

impl OutboundProtocol {
    /// Server address of the protocol payload.
    #[must_use]
    pub fn server(&self) -> &str {
        match self {
            Self::Vless(o) => &o.server,
            Self::Vmess(o) => &o.server,
            Self::Shadowsocks(o) => &o.server,
            Self::Trojan(o) => &o.server,
            Self::Hysteria2(o) => &o.server,
        }
    }

    /// Server port of the protocol payload.
    #[must_use]
    pub fn server_port(&self) -> u16 {
        match self {
            Self::Vless(o) => o.server_port,
            Self::Vmess(o) => o.server_port,
            Self::Shadowsocks(o) => o.server_port,
            Self::Trojan(o) => o.server_port,
            Self::Hysteria2(o) => o.server_port,
        }
    }
}

/// VLESS outbound (curated fields).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct VlessOutbound {
    #[serde(default)]
    pub server: String,
    #[serde(default)]
    pub server_port: u16,
    #[serde(default)]
    pub uuid: String,
    /// VLESS sub-protocol, e.g. `xtls-rprx-vision` (empty = none).
    #[serde(default)]
    pub flow: String,
    #[serde(default)]
    pub tls: OutboundTls,
    #[serde(default)]
    pub transport: OutboundTransport,
}

/// VMess outbound (curated fields).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct VmessOutbound {
    #[serde(default)]
    pub server: String,
    #[serde(default)]
    pub server_port: u16,
    #[serde(default)]
    pub uuid: String,
    /// Encryption method (`auto` / `none` / `aes-128-gcm` / `chacha20-poly1305`, …).
    #[serde(default)]
    pub security: String,
    /// Alter ID (`0` = AEAD).
    #[serde(default)]
    pub alter_id: u16,
    #[serde(default)]
    pub tls: OutboundTls,
    #[serde(default)]
    pub transport: OutboundTransport,
}

/// Shadowsocks outbound (curated fields).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ShadowsocksOutbound {
    #[serde(default)]
    pub server: String,
    #[serde(default)]
    pub server_port: u16,
    #[serde(default)]
    pub method: String,
    #[serde(default)]
    pub password: String,
}

/// Trojan outbound (curated fields).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TrojanOutbound {
    #[serde(default)]
    pub server: String,
    #[serde(default)]
    pub server_port: u16,
    #[serde(default)]
    pub password: String,
    #[serde(default)]
    pub tls: OutboundTls,
    #[serde(default)]
    pub transport: OutboundTransport,
}

/// Hysteria2 outbound (curated fields).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Hysteria2Outbound {
    #[serde(default)]
    pub server: String,
    #[serde(default)]
    pub server_port: u16,
    #[serde(default)]
    pub password: String,
    /// Max upload bandwidth in Mbps (0 = BBR congestion control).
    #[serde(default)]
    pub up_mbps: u32,
    /// Max download bandwidth in Mbps (0 = BBR congestion control).
    #[serde(default)]
    pub down_mbps: u32,
    #[serde(default)]
    pub obfs: Hysteria2Obfs,
    #[serde(default)]
    pub tls: OutboundTls,
}

/// Hysteria2 QUIC traffic obfuscator.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Hysteria2Obfs {
    /// Obfuscator type (`salamander` / `gecko`; empty = disabled).
    #[serde(default)]
    pub obfs_type: String,
    #[serde(default)]
    pub password: String,
}

/// Outbound TLS settings (curated fields).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutboundTls {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub server_name: String,
    #[serde(default)]
    pub insecure: bool,
    #[serde(default)]
    pub alpn: Vec<String>,
}

/// V2Ray transport settings (curated fields).
///
/// `kind` is the sing-box transport `type` (`tcp` / `ws` / `grpc` / `http` /
/// `quic` / `httpupgrade`). `path` maps to `path` (or `service_name` for gRPC)
/// and `host` to the transport's host / Host header.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutboundTransport {
    #[serde(default)]
    pub kind: String,
    #[serde(default)]
    pub path: String,
    #[serde(default)]
    pub host: String,
}

/// Build the forced `slice-` tag from a display name (ADR-0005 §3.1).
///
/// The name is lower-cased and slugified: unicode alphanumerics are kept,
/// every run of other characters becomes a single `-`, leading/trailing `-` are
/// trimmed. An empty result falls back to `slice-outbound` so the tag is never
/// just the bare prefix.
///
/// ```
/// use pp_client::config_slices::outbound_tag;
/// assert_eq!(outbound_tag("My Node 1"), "slice-my-node-1");
/// assert_eq!(outbound_tag("  !!!  "), "slice-outbound");
/// ```
#[must_use]
pub fn outbound_tag(name: &str) -> String {
    let mut slug = String::new();
    let mut pending_dash = false;
    for ch in name.trim().chars() {
        if ch.is_alphanumeric() {
            if pending_dash && !slug.is_empty() {
                slug.push('-');
            }
            pending_dash = false;
            slug.extend(ch.to_lowercase());
        } else {
            pending_dash = true;
        }
    }
    if slug.is_empty() {
        format!("{OUTBOUND_TAG_PREFIX}outbound")
    } else {
        format!("{OUTBOUND_TAG_PREFIX}{slug}")
    }
}
