[package]
name = "pp-client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["mitm", "scripts"]
mitm = ["dep:pp-mitm"]
scripts = ["dep:pp-script"]

[dependencies]
pp-common = { workspace = true }
pp-core = { workspace = true }
pp-mitm = { workspace = true, optional = true }
pp-script = { workspace = true, optional = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
flate2 = "1.0"
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tar = "0.4"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
urlencoding = "2"
uuid = { workspace = true }
zip = "2.2"

[dev-dependencies]
axum = { workspace = true }
tempfile = "3"
