[package]
name = "pp-client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
pp-common = { workspace = true }
pp-core = { workspace = true }
pp-mitm = { workspace = true }
pp-script = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
tempfile = "3"
