//! Local Override schema types (ADR-0002, section 3.1.1).
//!
//! Dual-core unified abstraction for client-side rule management.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Top-level container
// ---------------------------------------------------------------------------

/// Local Override container, isolated by core type.
///
/// Stored at `data_dir/local_override.json`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocalOverride {
    /// sing-box side local rules and rule sets.
    #[serde(default)]
    pub singbox: CoreLocalOverride,
    /// mihomo side local rules and rule sets.
    #[serde(default)]
    pub mihomo: CoreLocalOverride,
    /// Rule set subscription list (core-agnostic).
    #[serde(default)]
    pub rule_set_subscriptions: Vec<RuleSetSubscription>,
    /// Applied template records (for display / revert).
    #[serde(default)]
    pub applied_templates: Vec<AppliedTemplate>,
}

// ---------------------------------------------------------------------------
// Per-core override
// ---------------------------------------------------------------------------

/// Per-core local override.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CoreLocalOverride {
    /// User-defined rule cards (ordered).
    #[serde(default)]
    pub rules: Vec<LocalRule>,
    /// Rule set reference list (ordered, maps to rule_sets / rule-providers).
    #[serde(default)]
    pub rule_sets: Vec<LocalRuleSetRef>,
    /// Master switch for local override.
    #[serde(default = "default_true")]
    pub enabled: bool,
}

impl Default for CoreLocalOverride {
    fn default() -> Self {
        Self {
            rules: Vec::new(),
            rule_sets: Vec::new(),
            enabled: true,
        }
    }
}

// ---------------------------------------------------------------------------
// Local rule card
// ---------------------------------------------------------------------------

/// A single local rule (dual-core unified abstraction, translated per core).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocalRule {
    /// Unique rule ID (UUID v4 generated by frontend).
    pub id: String,
    /// User-defined name (optional, auto-generated summary when empty).
    #[serde(default)]
    pub name: String,
    /// Whether the rule is enabled.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Rule match type.
    pub match_type: RuleMatchType,
    /// Match target (semantics vary by match_type).
    pub target: String,
    /// Routing action.
    pub action: RuleAction,
    /// Advanced options.
    #[serde(default)]
    pub advanced: RuleAdvancedOptions,
    /// User note.
    #[serde(default)]
    pub note: String,
    /// Creation timestamp (for sort stability).
    pub created_at: u64,
    /// Sort weight (smaller = earlier).
    pub sort_order: i32,
}

/// Rule match type (aligned with sing-box route rule fields, translated for mihomo).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleMatchType {
    /// Exact domain match (sing-box: `domain` / mihomo: `DOMAIN`).
    Domain,
    /// Domain suffix match (sing-box: `domain_suffix` / mihomo: `DOMAIN-SUFFIX`).
    DomainSuffix,
    /// Domain keyword match (sing-box: `domain_keyword` / mihomo: `DOMAIN-KEYWORD`).
    DomainKeyword,
    /// IP CIDR (sing-box: `ip_cidr` / mihomo: `IP-CIDR` / `IP-CIDR6`).
    IpCidr,
    /// Source IP CIDR (sing-box: `source_ip_cidr` / mihomo: `SRC-IP-CIDR`).
    SourceIpCidr,
    /// Rule set reference (sing-box: `rule_set` / mihomo: `RULE-SET`).
    RuleSet,
    /// Android app package name (sing-box: `package_name` / mihomo: `PROCESS-NAME` approx).
    #[cfg(target_os = "android")]
    AppPackage,
    /// Process name (desktop, sing-box: `process_name` / mihomo: `PROCESS-NAME`).
    #[cfg(not(target_os = "android"))]
    ProcessName,
    /// Port range (sing-box: `port` / mihomo: `DST-PORT`).
    Port,
    /// Final catch-all rule (sing-box: `final` in route.final / mihomo: `MATCH`).
    ///
    /// Note: Final rule in the list is only a placeholder; actual write goes to
    /// route.final / MATCH in core config.
    Final,
}

/// Routing action.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleAction {
    /// Route to main selector / proxy group.
    Proxy,
    /// Direct connection.
    Direct,
    /// Reject.
    Reject,
    /// Route to specific outbound tag (advanced, target existence should be validated).
    Outbound { tag: String },
}

impl RuleAction {
    /// Returns the outbound tag string for core config generation.
    pub fn outbound_tag(&self) -> &str {
        match self {
            RuleAction::Proxy => "proxy",
            RuleAction::Direct => "direct",
            RuleAction::Reject => "reject",
            RuleAction::Outbound { tag } => tag.as_str(),
        }
    }
}

/// Advanced options for rules.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuleAdvancedOptions {
    /// Skip DNS resolution (only valid for domain-type rules).
    ///
    /// sing-box: no direct field, split `domain` + `ip_cidr` for semantics.
    /// mihomo: `no-resolve` flag.
    #[serde(default)]
    pub no_resolve: bool,
    /// Invert match.
    ///
    /// sing-box: `invert: true` / mihomo: simulated via logical rule `NOT`.
    #[serde(default)]
    pub invert: bool,
    /// Protocol sniff (sing-box 1.12+ action: sniff, not exposed to users yet).
    #[serde(skip)]
    pub _sniff: bool,
}

// ---------------------------------------------------------------------------
// Rule set reference
// ---------------------------------------------------------------------------

/// Rule set reference (locally downloaded or remote subscription).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocalRuleSetRef {
    pub id: String,
    /// Display name (user-visible).
    pub name: String,
    /// Tag used in core config references.
    pub tag: String,
    /// Rule set type.
    pub kind: RuleSetKind,
    /// Local file path (downloaded cache) or remote URL.
    pub source: RuleSetSource,
    /// Whether enabled.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Auto-update interval in minutes (0 = no auto-update).
    #[serde(default)]
    pub auto_update_interval_minutes: u32,
    /// Last update timestamp.
    #[serde(default)]
    pub last_updated: u64,
}

/// Rule set kind (core-specific format).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSetKind {
    /// sing-box: `remote` rule_set (binary .srs).
    SingBoxRemote,
    /// sing-box: `local` rule_set (source .json).
    SingBoxLocal,
    /// mihomo: `http` rule-provider.
    MihomoHttp,
    /// mihomo: `file` rule-provider.
    MihomoFile,
}

/// Rule set source.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSetSource {
    /// Remote URL (needs download cache).
    Remote { url: String },
    /// Local file path (already downloaded).
    Local { path: String },
    /// Built-in bundled resource (shipped with app).
    Bundled { name: String },
}

// ---------------------------------------------------------------------------
// Rule set subscription (core-agnostic market list)
// ---------------------------------------------------------------------------

/// Rule set subscription entry (unified list, core-agnostic).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuleSetSubscription {
    pub id: String,
    /// Community rule set identifier (e.g. `geoip-cn`, `geosite-ads`).
    pub community_id: String,
    /// Display name.
    pub display_name: String,
    /// Category tag.
    pub category: RuleSetCategory,
    /// Whether subscribed (checked).
    #[serde(default)]
    pub subscribed: bool,
    /// sing-box remote URL template (contains `{tag}` placeholder).
    pub singbox_url_template: String,
    /// mihomo remote URL template (contains `{tag}` placeholder).
    pub mihomo_url_template: String,
    /// Default auto-update interval in minutes.
    pub default_interval_minutes: u32,
}

/// Rule set category.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSetCategory {
    Geoip,
    Geosite,
    Ads,
    Privacy,
    Malware,
    Custom,
}

// ---------------------------------------------------------------------------
// Applied template record
// ---------------------------------------------------------------------------

/// Record of an applied scenario template.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AppliedTemplate {
    pub template_id: String,
    pub applied_at: u64,
    /// Rule IDs generated when applying (for one-click revert).
    pub generated_rule_ids: Vec<String>,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

#[inline]
#[must_use]
pub(crate) const fn default_true() -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn local_override_serde_roundtrip() {
        let orig = LocalOverride {
            singbox: CoreLocalOverride {
                rules: vec![LocalRule {
                    id: "r1".to_string(),
                    name: "test rule".to_string(),
                    enabled: true,
                    match_type: RuleMatchType::DomainSuffix,
                    target: "googleapis.com".to_string(),
                    action: RuleAction::Proxy,
                    advanced: RuleAdvancedOptions {
                        no_resolve: true,
                        invert: false,
                        _sniff: false,
                    },
                    note: "note".to_string(),
                    created_at: 1234567890,
                    sort_order: 0,
                }],
                rule_sets: vec![LocalRuleSetRef {
                    id: "rs1".to_string(),
                    name: "GeoIP CN".to_string(),
                    tag: "geoip-cn".to_string(),
                    kind: RuleSetKind::SingBoxRemote,
                    source: RuleSetSource::Remote {
                        url: "https://example.com/cn.srs".to_string(),
                    },
                    enabled: true,
                    auto_update_interval_minutes: 1440,
                    last_updated: 1234567890,
                }],
                enabled: true,
            },
            mihomo: CoreLocalOverride::default(),
            rule_set_subscriptions: vec![RuleSetSubscription {
                id: "sub1".to_string(),
                community_id: "geoip-cn".to_string(),
                display_name: "GeoIP China".to_string(),
                category: RuleSetCategory::Geoip,
                subscribed: true,
                singbox_url_template:
                    "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo-lite/ip/{tag}.srs"
                        .to_string(),
                mihomo_url_template:
                    "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo-lite/ip/{tag}.yaml"
                        .to_string(),
                default_interval_minutes: 1440,
            }],
            applied_templates: vec![AppliedTemplate {
                template_id: "return-china".to_string(),
                applied_at: 1234567890,
                generated_rule_ids: vec!["r1".to_string()],
            }],
        };

        let json = serde_json::to_string(&orig).unwrap();
        let back: LocalOverride = serde_json::from_str(&json).unwrap();
        assert_eq!(orig, back);
    }

    #[test]
    fn serde_missing_fields_defaults() {
        // Old local_override.json missing new fields should deserialize with defaults.
        let json = r#"{
            "singbox": {
                "rules": []
            }
        }"#;
        let parsed: LocalOverride = serde_json::from_str(json).unwrap();
        assert!(parsed.mihomo.rules.is_empty());
        assert!(parsed.rule_set_subscriptions.is_empty());
        assert!(parsed.applied_templates.is_empty());
        assert!(parsed.singbox.enabled); // default_true
    }

    #[test]
    fn rule_action_outbound_tag() {
        assert_eq!(RuleAction::Proxy.outbound_tag(), "proxy");
        assert_eq!(RuleAction::Direct.outbound_tag(), "direct");
        assert_eq!(RuleAction::Reject.outbound_tag(), "reject");
        assert_eq!(
            RuleAction::Outbound {
                tag: "custom".to_string()
            }
            .outbound_tag(),
            "custom"
        );
    }
}
