//! Local Override schema types (ADR-0002, section 3.1.1).
//!
//! Client-side rule management abstraction (sing-box only).

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Top-level container
// ---------------------------------------------------------------------------

/// Local Override container.
///
/// Stored at `data_dir/local_override.json`.
///
/// 存量兼容：旧版文件中的 `mihomo` 桶字段在反序列化时被静默丢弃（serde 忽略未知字段）。
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocalOverride {
    /// sing-box side local rules and rule sets.
    #[serde(default)]
    pub singbox: CoreLocalOverride,
    /// Legacy built-in rule set subscription list.
    ///
    /// **Deprecated**：内置规则集订阅机制已废弃，统一为用户自控的
    /// [`CustomRuleSet`] 模型。本字段仅保留 serde 兼容以读取旧版文件
    /// （存量迁移在 [`crate::local_override::store::LocalOverrideStore::load`]
    /// 中把 `subscribed == true` 的条目转换为 custom Remote 后清空）；
    /// 写回时恒为空数组，业务代码不得再依赖它。
    #[serde(default)]
    pub rule_set_subscriptions: Vec<RuleSetSubscription>,
    /// Applied template records (for display / revert).
    #[serde(default)]
    pub applied_templates: Vec<AppliedTemplate>,
    /// User-defined custom rule sets (remote URL download / manual source JSON).
    ///
    /// 旧版文件无此段时反序列化为空 Vec（`#[serde(default)]` 静默兼容）。
    #[serde(default)]
    pub custom_rule_sets: Vec<CustomRuleSet>,
    /// User-defined scenario templates (rule ID reference lists).
    ///
    /// 旧版文件无此段时反序列化为空 Vec（`#[serde(default)]` 静默兼容）。
    #[serde(default)]
    pub custom_templates: Vec<CustomTemplate>,
    /// User-added rule set market sources (remote catalog JSON URLs).
    ///
    /// 内置静态市场目录已取消，市场内容全部来自用户添加的远程目录源；每个源
    /// 的目录 JSON 缓存于 `data_dir/rulesets/market/<id>.json`。
    /// 旧版文件无此段时反序列化为空 Vec（`#[serde(default)]` 静默兼容）。
    #[serde(default)]
    pub market_sources: Vec<MarketSource>,
}

// ---------------------------------------------------------------------------
// Rule set market source (user-defined remote catalog)
// ---------------------------------------------------------------------------

/// A user-added rule set market source.
///
/// `url` 指向一个远程 JSON 目录（数组，条目格式见
/// [`crate::local_override::market::MarketEntry`]）；`last_fetched` 为最近一次
/// 成功拉取（添加或刷新）的 Unix 秒时间戳，0 表示尚未成功拉取。
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MarketSource {
    /// Unique source ID (UUID v4 generated by the backend).
    pub id: String,
    /// Display name (user-visible).
    pub name: String,
    /// Remote catalog JSON URL (unique among sources).
    pub url: String,
    /// Last successful fetch timestamp (Unix seconds; 0 = never).
    #[serde(default)]
    pub last_fetched: u64,
}

// ---------------------------------------------------------------------------
// Per-core override
// ---------------------------------------------------------------------------

/// Per-core local override.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CoreLocalOverride {
    /// User-defined rule cards (ordered).
    #[serde(default)]
    pub rules: Vec<LocalRule>,
    /// Rule set reference list (ordered, maps to rule_sets).
    #[serde(default)]
    pub rule_sets: Vec<LocalRuleSetRef>,
    /// Master switch for local override.
    #[serde(default = "default_true")]
    pub enabled: bool,
}

impl Default for CoreLocalOverride {
    fn default() -> Self {
        Self {
            rules: Vec::new(),
            rule_sets: Vec::new(),
            enabled: true,
        }
    }
}

// ---------------------------------------------------------------------------
// Local rule card
// ---------------------------------------------------------------------------

/// A single local rule (translated to sing-box route rule fields).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocalRule {
    /// Unique rule ID (UUID v4 generated by frontend).
    pub id: String,
    /// User-defined name (optional, auto-generated summary when empty).
    #[serde(default)]
    pub name: String,
    /// Whether the rule is enabled.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Rule match type.
    pub match_type: RuleMatchType,
    /// Match target (semantics vary by match_type).
    pub target: String,
    /// Routing action.
    pub action: RuleAction,
    /// Advanced options.
    #[serde(default)]
    pub advanced: RuleAdvancedOptions,
    /// User note.
    #[serde(default)]
    pub note: String,
    /// Creation timestamp (for sort stability).
    pub created_at: u64,
    /// Sort weight (smaller = earlier).
    pub sort_order: i32,
}

/// Rule match type (aligned with sing-box route rule fields).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleMatchType {
    /// Exact domain match (sing-box: `domain`).
    Domain,
    /// Domain suffix match (sing-box: `domain_suffix`).
    DomainSuffix,
    /// Domain keyword match (sing-box: `domain_keyword`).
    DomainKeyword,
    /// IP CIDR (sing-box: `ip_cidr`).
    IpCidr,
    /// Source IP CIDR (sing-box: `source_ip_cidr`).
    SourceIpCidr,
    /// Rule set reference (sing-box: `rule_set`).
    RuleSet,
    /// Android app package name (sing-box: `package_name`).
    #[cfg(target_os = "android")]
    AppPackage,
    /// Process name (desktop, sing-box: `process_name`).
    #[cfg(not(target_os = "android"))]
    ProcessName,
    /// Port range (sing-box: `port`).
    Port,
    /// Final catch-all rule (sing-box: `final` in route.final).
    ///
    /// Note: Final rule in the list is only a placeholder; actual write goes to
    /// route.final in core config.
    Final,
}

/// Routing action.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleAction {
    /// Route to main selector / proxy group.
    Proxy,
    /// Direct connection.
    Direct,
    /// Reject.
    Reject,
    /// Route to specific outbound tag (advanced, target existence should be validated).
    Outbound { tag: String },
}

impl RuleAction {
    /// Returns the outbound tag string for core config generation.
    pub fn outbound_tag(&self) -> &str {
        match self {
            RuleAction::Proxy => "proxy",
            RuleAction::Direct => "direct",
            RuleAction::Reject => "reject",
            RuleAction::Outbound { tag } => tag.as_str(),
        }
    }
}

/// Advanced options for rules.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuleAdvancedOptions {
    /// Skip DNS resolution (only valid for domain-type rules).
    ///
    /// sing-box: no direct field, split `domain` + `ip_cidr` for semantics.
    #[serde(default)]
    pub no_resolve: bool,
    /// Invert match.
    ///
    /// sing-box: `invert: true`.
    #[serde(default)]
    pub invert: bool,
    /// Protocol sniff (sing-box 1.12+ action: sniff, not exposed to users yet).
    #[serde(skip)]
    pub _sniff: bool,
}

// ---------------------------------------------------------------------------
// Rule set reference
// ---------------------------------------------------------------------------

/// Rule set reference (locally downloaded or remote subscription).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocalRuleSetRef {
    pub id: String,
    /// Display name (user-visible).
    pub name: String,
    /// Tag used in core config references.
    pub tag: String,
    /// Rule set type.
    pub kind: RuleSetKind,
    /// Local file path (downloaded cache) or remote URL.
    pub source: RuleSetSource,
    /// Whether enabled.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Auto-update interval in minutes (0 = no auto-update).
    #[serde(default)]
    pub auto_update_interval_minutes: u32,
    /// Last update timestamp.
    #[serde(default)]
    pub last_updated: u64,
}

/// Rule set kind.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSetKind {
    /// sing-box: `remote` rule_set (binary .srs).
    SingBoxRemote,
    /// sing-box: `local` rule_set (source .json).
    SingBoxLocal,
}

/// Rule set source.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSetSource {
    /// Remote URL (needs download cache).
    Remote { url: String },
    /// Local file path (already downloaded).
    Local { path: String },
    /// Built-in bundled resource (shipped with app).
    Bundled { name: String },
}

// ---------------------------------------------------------------------------
// Rule set subscription (core-agnostic market list)
// ---------------------------------------------------------------------------

/// Rule set subscription entry (unified list, core-agnostic).
///
/// **Deprecated**：内置规则集订阅机制已废弃。本类型仅保留 serde 兼容以读取
/// 旧版 `local_override.json`，存量迁移后会清空对应字段；新数据一律走
/// [`CustomRuleSet`]。
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuleSetSubscription {
    pub id: String,
    /// Community rule set identifier (e.g. `geoip-cn`, `geosite-ads`).
    pub community_id: String,
    /// Display name.
    pub display_name: String,
    /// Category tag.
    pub category: RuleSetCategory,
    /// Whether subscribed (checked).
    #[serde(default)]
    pub subscribed: bool,
    /// sing-box remote URL template (contains `{tag}` placeholder).
    pub singbox_url_template: String,
    /// Default auto-update interval in minutes.
    pub default_interval_minutes: u32,
}

/// Rule set category.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSetCategory {
    Geoip,
    Geosite,
    Ads,
    Privacy,
    Malware,
    Custom,
}

// ---------------------------------------------------------------------------
// Custom rule set (user-defined)
// ---------------------------------------------------------------------------

/// Rule set file format (aligned with sing-box rule_set `format` values).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RuleSetFormat {
    /// JSON source (`format: "source"`).
    Source,
    /// sing-box binary `.srs` (`format: "binary"`).
    Binary,
}

/// Where a custom rule set's content comes from.
///
/// Serialized internally-tagged (`"kind": "remote" | "manual"`) so the stored
/// `local_override.json` and the shell View/Input contract share one shape.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CustomRuleSetSource {
    /// Remote URL; content is downloaded and cached as a local file
    /// (`<data_dir>/rulesets/custom/<id>.srs|.json`) and injected as a local
    /// rule_set.
    Remote { url: String, format: RuleSetFormat },
    /// Manual sing-box rule_set source JSON pasted by the user; persisted to
    /// `<data_dir>/rulesets/custom/<id>.json` and injected as a local rule_set
    /// (`format: "source"`).
    Manual { content: String },
}

/// A user-defined rule set entry (remote URL / manual JSON).
///
/// 规则集是**纯资源**：不再有 `enabled` 概念（旧文件的 `enabled` 字段在
/// 反序列化时被 serde 静默忽略）。是否被使用只由引用它的规则决定——注入时
/// 仅注入「被注入规则引用 && backing 文件已存在」的规则集。
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustomRuleSet {
    /// Unique rule set ID (UUID v4 generated by frontend).
    pub id: String,
    /// Display name (user-visible).
    #[serde(default)]
    pub name: String,
    /// Tag used in core config rule_set references; must not collide with
    /// built-in `community_id`s or other custom tags.
    pub tag: String,
    /// Content source.
    pub source: CustomRuleSetSource,
    /// Last successful update timestamp (Remote only; 0 until first success).
    ///
    /// 语义为**本地缓存写入时间**（下载完成时刻）。
    #[serde(default)]
    pub last_updated: u64,
    /// Remote source's latest modification time (Remote only; 0 = unknown).
    ///
    /// 取自远端 `Last-Modified` 响应头（Unix 秒）；`remote_updated_at >
    /// last_updated` 即表示远端已有新版本（前端据此显示「有更新」标记）。
    /// 无该响应头时保持 0。旧版文件无此字段时 serde 默认 0。
    #[serde(default)]
    pub remote_updated_at: u64,
}

impl CustomRuleSet {
    /// Expected `RuleSetFormat` of this rule set's backing file.
    pub fn file_format(&self) -> RuleSetFormat {
        match self.source {
            CustomRuleSetSource::Remote { format, .. } => format,
            CustomRuleSetSource::Manual { .. } => RuleSetFormat::Source,
        }
    }
}

// ---------------------------------------------------------------------------
// Custom scenario template (rule ID references + apply activation)
// ---------------------------------------------------------------------------

/// A user-defined scenario template: a named, reusable **rule ID reference
/// list** (no snapshot copy).
///
/// `rules` holds the IDs of the (at creation time enabled) rule cards the
/// template was built from. Applying a template only records an
/// [`AppliedTemplate`] entry — it **does not copy or delete rules**; the
/// injected rules at startup are those that are `enabled` and whose ID is
/// referenced by an applied template (union across applied templates).
///
/// `template_id` used at apply / revert time is `"custom:<id>"` (see
/// [`crate::local_override::template::CUSTOM_TEMPLATE_PREFIX`]).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustomTemplate {
    /// Unique template ID (UUID v4 generated by frontend).
    pub id: String,
    /// Display name (user-visible, required by the create form).
    #[serde(default)]
    pub name: String,
    /// Optional description.
    #[serde(default)]
    pub desc: String,
    /// Rule card ID references (not snapshots). Stale references (missing /
    /// disabled rule) are kept on purpose and skipped at injection time —
    /// [`crate::local_override::template::template_invalid_refs`] reports them.
    #[serde(default)]
    pub rules: Vec<String>,
    /// Creation timestamp.
    pub created_at: u64,
}

// ---------------------------------------------------------------------------
// Applied template record
// ---------------------------------------------------------------------------

/// Record of an applied scenario template (a scenario switch).
///
/// Applying only records `template_id` + `applied_at`; **no rules are copied**
/// and no rules are owned by this record. `generated_rule_ids` is deprecated
/// (kept for serde compatibility with legacy files; new writes always use an
/// empty Vec) — injection is derived live from the referenced template's rule
/// IDs, and reverting only removes this record.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AppliedTemplate {
    pub template_id: String,
    pub applied_at: u64,
    /// **Deprecated**：snapshot-copy 时代的产物。引用语义下不再使用；保留字段
    /// 仅 serde 兼容旧文件，新写入恒为空 Vec。
    #[serde(default)]
    pub generated_rule_ids: Vec<String>,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

#[inline]
#[must_use]
pub(crate) const fn default_true() -> bool {
    true
}

#[cfg(test)]
#[path = "tests/schema_tests.rs"]
mod tests;
