//! Scenario templates: user-defined custom templates ([`CustomTemplate`]).
//!
//! 内置场景模板机制（return-china / overseas / ad-filter）已废弃；`apply_template`
//! 只接受 `"custom:<id>"` 形式的用户自定义模板地址（[`CUSTOM_TEMPLATE_PREFIX`]）。
//! 应用即把模板快照规则以新 UUID 复制后头插到 `singbox.rules`，并记录
//! [`AppliedTemplate`] 供 [`revert_template`] 撤销。
//!
//! 自「废弃内置机制」起，应用模板**不再自动订阅**任何规则集：快照中的
//! `rule_set` 规则原样复制，其 tag 是否可注入由用户自控的
//! [`CustomRuleSet`](super::CustomRuleSet)（启用 + 有落盘文件）决定。
//!
//! ADR-0002, section 3.3.

use std::collections::HashSet;

use pp_common::{PanelError, PanelResult};

use super::{AppliedTemplate, CustomTemplate, LocalOverride, LocalRule};

/// Prefix distinguishing a user-defined template ID from built-in ones.
///
/// Apply / revert commands receive `"custom:<id>"` as the `template_id`.
pub const CUSTOM_TEMPLATE_PREFIX: &str = "custom:";

/// Apply a scenario template to the given [`LocalOverride`].
///
/// Custom templates (`template_id = "custom:<id>"`, [`CUSTOM_TEMPLATE_PREFIX`]):
/// copies the snapshot rules with fresh UUIDs, head-inserts them and records
/// `applied_templates` with `template_id = "custom:<id>"`.
///
/// # Errors
///
/// Returns error if `template_id` is not `"custom:<id>"` or the custom template
/// does not exist.
pub fn apply_template(
    ovr: &mut LocalOverride,
    template_id: &str,
    now_sec: u64,
) -> PanelResult<Vec<String>> {
    let Some(custom_id) = template_id.strip_prefix(CUSTOM_TEMPLATE_PREFIX) else {
        return Err(PanelError::Client(format!(
            "unknown template id '{template_id}' (only custom templates, addressed as '{CUSTOM_TEMPLATE_PREFIX}<id>', are supported)"
        )));
    };

    let template: CustomTemplate = ovr
        .custom_templates
        .iter()
        .find(|t| t.id == custom_id)
        .cloned()
        .ok_or_else(|| PanelError::Client(format!("custom template not found: {custom_id}")))?;

    let min_order = min_sort_order(&ovr.singbox.rules);
    let base_order = min_order.saturating_sub(100);

    let generated: Vec<LocalRule> = template
        .rules
        .into_iter()
        .enumerate()
        .map(|(i, mut rule)| {
            rule.id = uuid::Uuid::new_v4().to_string();
            rule.created_at = now_sec;
            rule.sort_order = base_order + i as i32;
            rule
        })
        .collect();
    let rule_ids: Vec<String> = generated.iter().map(|r| r.id.clone()).collect();

    ovr.singbox.rules.extend(generated);

    ovr.applied_templates.push(AppliedTemplate {
        template_id: template_id.to_string(),
        applied_at: now_sec,
        generated_rule_ids: rule_ids.clone(),
    });

    Ok(rule_ids)
}

/// Revert (undo) a previously applied template by its ID.
///
/// Removes all rules whose IDs were generated by the template, and removes
/// the [`AppliedTemplate`] record.
///
/// Returns `true` if a template was found and reverted.
pub fn revert_template(ovr: &mut LocalOverride, template_id: &str) -> bool {
    let Some(idx) = ovr
        .applied_templates
        .iter()
        .position(|t| t.template_id == template_id)
    else {
        return false;
    };

    let record = ovr.applied_templates.remove(idx);
    let ids_to_remove: HashSet<String> = record.generated_rule_ids.into_iter().collect();

    ovr.singbox.rules.retain(|r| !ids_to_remove.contains(&r.id));

    true
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn min_sort_order(rules: &[LocalRule]) -> i32 {
    rules.iter().map(|r| r.sort_order).min().unwrap_or(0)
}

#[cfg(test)]
#[path = "tests/template_tests.rs"]
mod tests;
