//! Scenario templates: return-china, overseas, ad-filter.
//!
//! Templates are pre-defined rule combinations. Applying a template
//! auto-subscribes the community rule sets it depends on
//! ([`template_rule_set_dependencies`]), then generates multiple [`LocalRule`]
//! entries (including the `rule_set` rules, unconditionally) and records an
//! [`AppliedTemplate`] for revert.
//!
//! ADR-0002, section 3.3.

use std::collections::HashSet;

use pp_common::{PanelError, PanelResult};

use super::{AppliedTemplate, LocalOverride, LocalRule, RuleAction, RuleMatchType};

/// Built-in template identifiers.
pub const TEMPLATE_RETURN_CHINA: &str = "return-china";
pub const TEMPLATE_OVERSEAS: &str = "overseas";
pub const TEMPLATE_AD_FILTER: &str = "ad-filter";

/// All built-in template IDs.
pub const BUILT_IN_TEMPLATE_IDS: &[&str] =
    &[TEMPLATE_RETURN_CHINA, TEMPLATE_OVERSEAS, TEMPLATE_AD_FILTER];

/// Community rule sets a built-in template depends on.
///
/// Applying a template auto-subscribes these rule sets (the generated
/// `rule_set` rules resolve only after the rule sets are downloaded), per
/// ADR-0002 section 3.3.3.
///
/// Returns an empty slice for unknown template IDs.
pub fn template_rule_set_dependencies(template_id: &str) -> &'static [&'static str] {
    match template_id {
        TEMPLATE_RETURN_CHINA => &["geoip-cn", "geosite-cn"],
        TEMPLATE_OVERSEAS => &["geosite-geolocation-!cn"],
        TEMPLATE_AD_FILTER => &["geosite-ads"],
        _ => &[],
    }
}

/// Apply a scenario template to the given [`LocalOverride`].
///
/// - Auto-subscribes the community rule sets the template depends on
///   ([`template_rule_set_dependencies`]); IDs not present in
///   `rule_set_subscriptions` are skipped defensively.
/// - Generates rules with fresh UUIDs; the `rule_set` rules are always
///   generated, regardless of prior subscription state.
/// - Inserts rules at the head of the list (`sort_order = min - 100`).
/// - Records the applied template for later revert.
/// - Returns the generated rule IDs.
///
/// # Errors
///
/// Returns error if `template_id` is unknown.
pub fn apply_template(
    ovr: &mut LocalOverride,
    template_id: &str,
    now_sec: u64,
) -> PanelResult<Vec<String>> {
    // Auto-subscribe the dependency rule sets so the generated rule_set rules
    // take effect once the rule sets are downloaded. Unknown IDs are skipped
    // (the built-in list covers every dependency, so this is only defensive).
    for &community_id in template_rule_set_dependencies(template_id) {
        if let Some(sub) = ovr
            .rule_set_subscriptions
            .iter_mut()
            .find(|s| s.community_id.as_str() == community_id)
        {
            sub.subscribed = true;
        } else {
            tracing::debug!(
                community_id,
                "template dependency rule set not in subscription list, skipping"
            );
        }
    }

    let generated = match template_id {
        TEMPLATE_RETURN_CHINA => generate_return_china_rules(now_sec),
        TEMPLATE_OVERSEAS => generate_overseas_rules(now_sec),
        TEMPLATE_AD_FILTER => generate_ad_filter_rules(now_sec),
        _ => {
            return Err(PanelError::Client(format!(
                "unknown template id: {template_id}"
            )));
        }
    };

    let rule_ids: Vec<String> = generated.iter().map(|r| r.id.clone()).collect();

    // Insert generated rules.
    let min_order = min_sort_order(&ovr.singbox.rules);
    let base_order = min_order.saturating_sub(100);

    for (i, mut rule) in generated.into_iter().enumerate() {
        rule.sort_order = base_order + i as i32;
        ovr.singbox.rules.push(rule);
    }

    // Record applied template.
    ovr.applied_templates.push(AppliedTemplate {
        template_id: template_id.to_string(),
        applied_at: now_sec,
        generated_rule_ids: rule_ids.clone(),
    });

    Ok(rule_ids)
}

/// Revert (undo) a previously applied template by its ID.
///
/// Removes all rules whose IDs were generated by the template, and removes
/// the [`AppliedTemplate`] record.
///
/// Returns `true` if a template was found and reverted.
pub fn revert_template(ovr: &mut LocalOverride, template_id: &str) -> bool {
    let Some(idx) = ovr
        .applied_templates
        .iter()
        .position(|t| t.template_id == template_id)
    else {
        return false;
    };

    let record = ovr.applied_templates.remove(idx);
    let ids_to_remove: HashSet<String> = record.generated_rule_ids.into_iter().collect();

    ovr.singbox.rules.retain(|r| !ids_to_remove.contains(&r.id));

    true
}

// ---------------------------------------------------------------------------
// Template generators
// ---------------------------------------------------------------------------

/// Return-China template:
/// 1. domain_suffix: [cn, com.cn, net.cn] → direct
/// 2. rule_set: geoip-cn → direct
/// 3. rule_set: geosite-cn → direct
fn generate_return_china_rules(now_sec: u64) -> Vec<LocalRule> {
    // rule_set references are always generated; the dependency rule sets are
    // auto-subscribed when the template is applied.
    vec![
        LocalRule {
            id: uuid::Uuid::new_v4().to_string(),
            name: "China TLD direct".to_string(),
            enabled: true,
            match_type: RuleMatchType::DomainSuffix,
            target: "cn".to_string(),
            action: RuleAction::Direct,
            advanced: Default::default(),
            note: "Auto-generated by return-china template".to_string(),
            created_at: now_sec,
            sort_order: 0,
        },
        LocalRule {
            id: uuid::Uuid::new_v4().to_string(),
            name: "com.cn direct".to_string(),
            enabled: true,
            match_type: RuleMatchType::DomainSuffix,
            target: "com.cn".to_string(),
            action: RuleAction::Direct,
            advanced: Default::default(),
            note: "Auto-generated by return-china template".to_string(),
            created_at: now_sec,
            sort_order: 0,
        },
        LocalRule {
            id: uuid::Uuid::new_v4().to_string(),
            name: "net.cn direct".to_string(),
            enabled: true,
            match_type: RuleMatchType::DomainSuffix,
            target: "net.cn".to_string(),
            action: RuleAction::Direct,
            advanced: Default::default(),
            note: "Auto-generated by return-china template".to_string(),
            created_at: now_sec,
            sort_order: 0,
        },
        LocalRule {
            id: uuid::Uuid::new_v4().to_string(),
            name: "GeoIP CN direct".to_string(),
            enabled: true,
            match_type: RuleMatchType::RuleSet,
            target: "geoip-cn".to_string(),
            action: RuleAction::Direct,
            advanced: Default::default(),
            note: "Auto-generated by return-china template".to_string(),
            created_at: now_sec,
            sort_order: 0,
        },
        LocalRule {
            id: uuid::Uuid::new_v4().to_string(),
            name: "GeoSite CN direct".to_string(),
            enabled: true,
            match_type: RuleMatchType::RuleSet,
            target: "geosite-cn".to_string(),
            action: RuleAction::Direct,
            advanced: Default::default(),
            note: "Auto-generated by return-china template".to_string(),
            created_at: now_sec,
            sort_order: 0,
        },
    ]
}

/// Overseas template:
/// 1. domain_suffix: [google.com, youtube.com, github.com] → proxy
/// 2. rule_set: geosite-geolocation-!cn → proxy
fn generate_overseas_rules(now_sec: u64) -> Vec<LocalRule> {
    let mut rules = Vec::new();

    for domain in ["google.com", "youtube.com", "github.com"] {
        rules.push(LocalRule {
            id: uuid::Uuid::new_v4().to_string(),
            name: format!("{domain} proxy"),
            enabled: true,
            match_type: RuleMatchType::DomainSuffix,
            target: domain.to_string(),
            action: RuleAction::Proxy,
            advanced: Default::default(),
            note: "Auto-generated by overseas template".to_string(),
            created_at: now_sec,
            sort_order: 0,
        });
    }

    // rule_set reference is always generated; the dependency rule set is
    // auto-subscribed when the template is applied.
    rules.push(LocalRule {
        id: uuid::Uuid::new_v4().to_string(),
        name: "Non-China geolocation proxy".to_string(),
        enabled: true,
        match_type: RuleMatchType::RuleSet,
        target: "geosite-geolocation-!cn".to_string(),
        action: RuleAction::Proxy,
        advanced: Default::default(),
        note: "Auto-generated by overseas template".to_string(),
        created_at: now_sec,
        sort_order: 0,
    });

    rules
}

/// Ad-Filter template:
/// 1. rule_set: geosite-ads → reject
/// 2. rule_set: geosite-category-ads-all → reject
fn generate_ad_filter_rules(now_sec: u64) -> Vec<LocalRule> {
    // rule_set reference is always generated; the dependency rule set is
    // auto-subscribed when the template is applied.
    vec![LocalRule {
        id: uuid::Uuid::new_v4().to_string(),
        name: "Ad domains reject".to_string(),
        enabled: true,
        match_type: RuleMatchType::RuleSet,
        target: "geosite-ads".to_string(),
        action: RuleAction::Reject,
        advanced: Default::default(),
        note: "Auto-generated by ad-filter template".to_string(),
        created_at: now_sec,
        sort_order: 0,
    }]
    // geosite-category-ads-all is the same as geosite-ads in our built-in list;
    // we use the community_id "geosite-ads" which maps to category-ads-all.
    // Skip duplicate if same.
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn min_sort_order(rules: &[LocalRule]) -> i32 {
    rules.iter().map(|r| r.sort_order).min().unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::local_override::store::built_in_rule_set_subscriptions;

    fn empty_override() -> LocalOverride {
        LocalOverride {
            rule_set_subscriptions: built_in_rule_set_subscriptions(),
            ..Default::default()
        }
    }

    fn is_subscribed_to(ovr: &LocalOverride, community_id: &str) -> bool {
        ovr.rule_set_subscriptions
            .iter()
            .any(|s| s.community_id == community_id && s.subscribed)
    }

    fn rule_set_rules(ovr: &LocalOverride) -> impl Iterator<Item = &LocalRule> + '_ {
        ovr.singbox
            .rules
            .iter()
            .filter(|r| r.match_type == RuleMatchType::RuleSet)
    }

    #[test]
    fn template_dependency_mapping() {
        assert_eq!(
            template_rule_set_dependencies(TEMPLATE_RETURN_CHINA),
            &["geoip-cn", "geosite-cn"]
        );
        assert_eq!(
            template_rule_set_dependencies(TEMPLATE_OVERSEAS),
            &["geosite-geolocation-!cn"]
        );
        assert_eq!(
            template_rule_set_dependencies(TEMPLATE_AD_FILTER),
            &["geosite-ads"]
        );
        assert!(template_rule_set_dependencies("unknown").is_empty());
    }

    #[test]
    fn apply_return_china_template_generates_rules() {
        // Not pre-subscribed: apply must still generate the rule_set rules and
        // auto-subscribe the dependency rule sets.
        let mut ovr = empty_override();
        assert!(!is_subscribed_to(&ovr, "geoip-cn"));
        assert!(!is_subscribed_to(&ovr, "geosite-cn"));

        let ids = apply_template(&mut ovr, TEMPLATE_RETURN_CHINA, 1000).unwrap();
        assert!(!ids.is_empty());
        assert_eq!(ovr.singbox.rules.len(), ids.len());
        assert_eq!(ovr.applied_templates.len(), 1);
        assert_eq!(ovr.applied_templates[0].template_id, TEMPLATE_RETURN_CHINA);

        let rs_targets: Vec<&str> = rule_set_rules(&ovr).map(|r| r.target.as_str()).collect();
        assert!(rs_targets.contains(&"geoip-cn"));
        assert!(rs_targets.contains(&"geosite-cn"));
    }

    #[test]
    fn apply_overseas_template_generates_rules() {
        let mut ovr = empty_override();

        let ids = apply_template(&mut ovr, TEMPLATE_OVERSEAS, 2000).unwrap();
        assert!(!ids.is_empty());
        assert!(ovr.singbox.rules.iter().any(|r| r.target == "google.com"));
        assert!(ovr.singbox.rules.iter().any(|r| r.target == "youtube.com"));
        assert!(ovr.singbox.rules.iter().any(|r| r.target == "github.com"));
        assert!(rule_set_rules(&ovr).any(|r| r.target == "geosite-geolocation-!cn"));
    }

    #[test]
    fn apply_ad_filter_template_generates_rules() {
        // Regression: previously unsubscribed ad-filter generated 0 rules.
        let mut ovr = empty_override();

        let ids = apply_template(&mut ovr, TEMPLATE_AD_FILTER, 3000).unwrap();
        assert!(!ids.is_empty());
        assert_eq!(ids.len(), 1);
        let reject = rule_set_rules(&ovr)
            .find(|r| r.target == "geosite-ads" && r.action == RuleAction::Reject);
        assert!(reject.is_some());
    }

    #[test]
    fn apply_template_auto_subscribes_dependency_rule_sets() {
        // return-china → geoip-cn + geosite-cn.
        let mut ovr = empty_override();
        apply_template(&mut ovr, TEMPLATE_RETURN_CHINA, 1000).unwrap();
        assert!(is_subscribed_to(&ovr, "geoip-cn"));
        assert!(is_subscribed_to(&ovr, "geosite-cn"));

        // overseas → geosite-geolocation-!cn.
        let mut ovr = empty_override();
        apply_template(&mut ovr, TEMPLATE_OVERSEAS, 2000).unwrap();
        assert!(is_subscribed_to(&ovr, "geosite-geolocation-!cn"));

        // ad-filter → geosite-ads.
        let mut ovr = empty_override();
        apply_template(&mut ovr, TEMPLATE_AD_FILTER, 3000).unwrap();
        assert!(is_subscribed_to(&ovr, "geosite-ads"));

        // Unknown templates subscribe nothing.
        let mut ovr = empty_override();
        assert!(apply_template(&mut ovr, "unknown", 1000).is_err());
        assert!(ovr.rule_set_subscriptions.iter().all(|s| !s.subscribed));
    }

    #[test]
    fn revert_template_removes_generated_rules() {
        let mut ovr = empty_override();

        let before_count = ovr.singbox.rules.len();
        apply_template(&mut ovr, TEMPLATE_RETURN_CHINA, 1000).unwrap();
        assert!(ovr.singbox.rules.len() > before_count);
        assert!(is_subscribed_to(&ovr, "geoip-cn"));

        let reverted = revert_template(&mut ovr, TEMPLATE_RETURN_CHINA);
        assert!(reverted);
        assert_eq!(ovr.singbox.rules.len(), before_count);
        assert!(ovr.applied_templates.is_empty());

        // Revert only removes generated rules; re-apply works normally.
        let ids = apply_template(&mut ovr, TEMPLATE_RETURN_CHINA, 2000).unwrap();
        assert!(!ids.is_empty());
        assert!(
            ovr.applied_templates
                .iter()
                .any(|t| t.template_id == TEMPLATE_RETURN_CHINA)
        );
    }

    #[test]
    fn revert_unknown_template_returns_false() {
        let mut ovr = empty_override();
        let reverted = revert_template(&mut ovr, "nonexistent");
        assert!(!reverted);
    }

    #[test]
    fn apply_unknown_template_errors() {
        let mut ovr = empty_override();
        let result = apply_template(&mut ovr, "unknown", 1000);
        assert!(result.is_err());
    }

    #[test]
    fn template_rules_have_unique_ids() {
        let mut ovr = empty_override();

        let ids = apply_template(&mut ovr, TEMPLATE_RETURN_CHINA, 1000).unwrap();
        let unique: std::collections::HashSet<_> = ids.iter().collect();
        assert_eq!(unique.len(), ids.len());
    }
}
