[application]
name = "proxy-panel-web"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "ProxyPanel"
base_path = "/"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []

[web.resource.dev]
style = []
