//! Sea-ORM entities (generated from migrations).
//!
//! In a real workflow these would be generated by `sea-orm-cli generate entity`.
//! For the initial architecture we define them by hand to match the migration schema.

pub mod client;
pub mod host_metric;
pub mod node;
pub mod node_binding;
pub mod protocol_config;
pub mod subscription;
pub mod subscription_template;
pub mod system_log;
pub mod traffic_record;
pub mod user;

pub use client::Entity as Client;
pub use host_metric::Entity as HostMetric;
pub use node::Entity as Node;
pub use node_binding::Entity as NodeBinding;
pub use protocol_config::Entity as ProtocolConfig;
pub use subscription::Entity as Subscription;
pub use subscription_template::Entity as SubscriptionTemplate;
pub use system_log::Entity as SystemLog;
pub use traffic_record::Entity as TrafficRecord;
pub use user::Entity as User;
