//! Sea-ORM entities (generated from migrations).
//!
//! In a real workflow these would be generated by `sea-orm-cli generate entity`.
//! For the initial architecture we define them by hand to match the migration schema.

pub mod agent_log;
pub mod api_key;
pub mod certificate;
pub mod client;
pub mod client_group_binding;
pub mod client_online_session;
pub mod core_version;
pub mod host_metric;
pub mod inbound_host;
pub mod node;
pub mod node_binding;
pub mod node_binding_group_binding;
pub mod node_group;
pub mod node_user_usage_record;
pub mod protocol_config;
pub mod subscription;
pub mod subscription_template;
pub mod system_log;
pub mod system_meta;
pub mod traffic_record;
pub mod user;
pub mod webhook;

pub use agent_log::Entity as AgentLog;
pub use api_key::Entity as ApiKey;
pub use certificate::Entity as Certificate;
pub use client::Entity as Client;
pub use client_group_binding::Entity as ClientGroupBinding;
pub use client_online_session::Entity as ClientOnlineSession;
pub use core_version::Entity as CoreVersion;
pub use host_metric::Entity as HostMetric;
pub use inbound_host::Entity as InboundHost;
pub use node::Entity as Node;
pub use node_binding::Entity as NodeBinding;
pub use node_binding_group_binding::Entity as NodeBindingGroupBinding;
pub use node_group::Entity as NodeGroup;
pub use node_user_usage_record::Entity as NodeUserUsageRecord;
pub use protocol_config::Entity as ProtocolConfig;
pub use subscription::Entity as Subscription;
pub use subscription_template::Entity as SubscriptionTemplate;
pub use system_log::Entity as SystemLog;
pub use system_meta::Entity as SystemMeta;
pub use traffic_record::Entity as TrafficRecord;
pub use user::Entity as User;
pub use webhook::Entity as Webhook;
