[package]
name = "pp-common"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
hex = "0.4"
sha2 = { workspace = true }
argon2 = { workspace = true }
sea-orm = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
subtle = "2.6"
x25519-dalek = { version = "2.0", features = ["static_secrets", "getrandom"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_NetworkManagement_IpHelper",
  "Win32_Networking_WinSock",
  "Win32_Security",
  "Win32_System_JobObjects",
  "Win32_System_Threading",
] }
