[package]
name = "pp-common"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
hex = "0.4"
sha2 = { workspace = true }
argon2 = { workspace = true }
sea-orm = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
subtle = "2.6"
x25519-dalek = { version = "2.0", features = ["static_secrets", "getrandom"] }
