/**
 * Config slices (ADR-0005 P0) API types and functions.
 *
 * Aligned with Rust `pp_client::config_slices` (`dns.rs` / `outbound.rs` /
 * `schema.rs`). The Tauri commands take/return the full [`ConfigSlices`]
 * document directly (no View/Input split): `config_slices_save` is a full-patch
 * and validates server-side before writing, so a validation failure rejects
 * without touching `data_dir/config_slices.json`.
 */

import { invoke } from "@tauri-apps/api/core";

/** Current slice schema version (mirrors Rust `SLICE_VERSION`). */
export const SLICE_VERSION = 2;

// ---------------------------------------------------------------------------
// DNS slice
// ---------------------------------------------------------------------------

/** Platform DNS mode (ADR-0005 D1). */
export type DnsMode = "follow_system" | "takeover";

/** Domain resolution strategy (maps to sing-box `strategy` / `domain_strategy`). */
export type DnsStrategy = "prefer_ipv4" | "prefer_ipv6" | "ipv4_only" | "ipv6_only";

/** DNS server type (`dns.servers[].type`). */
export type DnsServerType = "udp" | "tls" | "https" | "quic" | "h3" | "local" | "fakeip";

/** DNS rule match type (determines the sing-box match field). */
export type DnsMatchType =
  | "domain"
  | "domain_suffix"
  | "domain_keyword"
  | "rule_set"
  | "query_type"
  /** Outbound mode; target is a single `rule` / `global` / `direct` value (rendered as a string). */
  | "clash_mode";

/** DNS rule action (`dns.rules[].action`). */
export type DnsRuleAction = "route" | "predefined" | "reject";

/** A single DNS server (curated fields). */
export interface DnsServer {
  /** Unique tag within the slice; referenced by `rules` and `final_tag`. */
  tag: string;
  /** Server address (IP or domain); unused for `local` and `fakeip`. */
  server: string;
  server_type: DnsServerType;
  /** Server port (sing-box default per type when `null`). */
  server_port: number | null;
  /**
   * FakeIP IPv4 range (`fakeip` type only); empty renders sing-box's default
   * `198.18.0.0/15`.
   *
   * Mirrors the Rust `String` + `#[serde(default)]` field: the wire form is
   * always a string (possibly empty), never `null`.
   */
  inet4_range: string;
  /** FakeIP IPv6 range (`fakeip` type only); empty omits the field. */
  inet6_range: string;
  /** Upstream outbound tag (empty = default direct dial). */
  detour: string;
  /**
   * Per-server strategy override.
   *
   * Not rendered: sing-box 1.12+ new DNS servers have no per-server query
   * strategy field. Kept for schema completeness / future use.
   */
  strategy: DnsStrategy | null;
  /** DNS server tag used to resolve this server's own domain. */
  domain_resolver: string;
}

/** A single DNS routing rule (rendered to `dns.rules[]`). */
export interface DnsRule {
  /** Unique rule ID (UUID v4 generated by the frontend). */
  id: string;
  enabled: boolean;
  match_type: DnsMatchType;
  /**
   * Match target (semantics depend on `match_type`).
   *
   * For `query_type` this is a comma-separated list (e.g. `A,AAAA`).
   */
  target: string;
  /** Target DNS server tag (`action: "route"`). */
  server_tag: string;
  /** Rule action (`route` default; `predefined` / `reject`). */
  action: DnsRuleAction;
  /** Response code for `predefined` (empty = `NOERROR`). */
  rcode: string;
}

/** DNS slice: structured form of the sing-box top-level `dns` object. */
export interface DnsSlice {
  /** Platform DNS mode: `follow_system` never injects the slice body. */
  mode: DnsMode;
  servers: DnsServer[];
  rules: DnsRule[];
  /** Default server tag (sing-box `dns.final`); required when takeover is on. */
  final_tag: string;
  /** Default domain strategy (sing-box `dns.strategy`). */
  strategy: DnsStrategy;
  /** Reverse mapping (sing-box `dns.reverse_mapping`); rendered only when `true`. */
  reverse_mapping: boolean;
}

// ---------------------------------------------------------------------------
// Custom outbound slice
// ---------------------------------------------------------------------------

/** Outbound TLS settings (curated fields). */
export interface OutboundTls {
  enabled: boolean;
  server_name: string;
  insecure: boolean;
  alpn: string[];
}

/**
 * V2Ray transport settings (curated fields).
 *
 * `kind` is the sing-box transport `type` (`tcp` / `ws` / `grpc` / `http` /
 * `quic` / `httpupgrade`). `path` maps to `path` (or `service_name` for gRPC)
 * and `host` to the transport's host / Host header.
 */
export interface OutboundTransport {
  kind: string;
  path: string;
  host: string;
}

/** Hysteria2 QUIC traffic obfuscator. */
export interface Hysteria2Obfs {
  /** Obfuscator type (`salamander` / `gecko`; empty = disabled). */
  obfs_type: string;
  password: string;
}

/** VLESS outbound (curated fields). */
export interface VlessOutbound {
  type: "vless";
  server: string;
  server_port: number;
  uuid: string;
  /** VLESS sub-protocol, e.g. `xtls-rprx-vision` (empty = none). */
  flow: string;
  tls: OutboundTls;
  transport: OutboundTransport;
}

/** VMess outbound (curated fields). */
export interface VmessOutbound {
  type: "vmess";
  server: string;
  server_port: number;
  uuid: string;
  /** Encryption method (`auto` / `none` / `aes-128-gcm` / `chacha20-poly1305`, …). */
  security: string;
  /** Alter ID (`0` = AEAD). */
  alter_id: number;
  tls: OutboundTls;
  transport: OutboundTransport;
}

/** Shadowsocks outbound (curated fields). */
export interface ShadowsocksOutbound {
  type: "shadowsocks";
  server: string;
  server_port: number;
  method: string;
  password: string;
}

/** Trojan outbound (curated fields). */
export interface TrojanOutbound {
  type: "trojan";
  server: string;
  server_port: number;
  password: string;
  tls: OutboundTls;
  transport: OutboundTransport;
}

/** Hysteria2 outbound (curated fields). */
export interface Hysteria2Outbound {
  type: "hysteria2";
  server: string;
  server_port: number;
  password: string;
  /** Max upload bandwidth in Mbps (0 = BBR congestion control). */
  up_mbps: number;
  /** Max download bandwidth in Mbps (0 = BBR congestion control). */
  down_mbps: number;
  obfs: Hysteria2Obfs;
  tls: OutboundTls;
}

/**
 * Selector outbound: manually picks one member outbound (Clash API controlled).
 *
 * Fields mirror Rust `SelectorOutbound` (sing-box 1.14 `outbound/selector`).
 */
export interface SelectorOutbound {
  type: "selector";
  /** Member outbound tags to select from (required, must not be empty). */
  outbounds: string[];
  /** Default member tag; the first member is used when empty. */
  default: string;
  /** Interrupt existing connections when the selection changes. */
  interrupt_exist_connections: boolean;
}

/**
 * URLTest outbound: automatically picks the lowest-latency member.
 *
 * Fields mirror Rust `UrlTestOutbound` (sing-box 1.14 `outbound/urltest`). The
 * type discriminator is `urltest` (no underscore) to match the Rust explicit
 * `#[serde(rename = "urltest")]`.
 */
export interface UrlTestOutbound {
  type: "urltest";
  /** Member outbound tags to test (required, must not be empty). */
  outbounds: string[];
  /** Test URL (empty = sing-box default `https://www.gstatic.com/generate_204`). */
  url: string;
  /** Test interval as a duration string (e.g. `3m`; empty = sing-box default). */
  interval: string;
  /** Test tolerance in milliseconds (`0` = sing-box default). */
  tolerance: number;
  /** Interrupt existing connections when the selected outbound changes. */
  interrupt_exist_connections: boolean;
}

/**
 * Protocol-specific outbound payload.
 *
 * Mirrors the Rust internally-tagged enum (`tag = "type"`): the discriminant is
 * flattened onto the containing `CustomOutbound`, so it sits next to
 * `id` / `name` / `enabled` and the protocol fields.
 */
export type OutboundProtocol =
  | VlessOutbound
  | VmessOutbound
  | ShadowsocksOutbound
  | TrojanOutbound
  | Hysteria2Outbound
  | SelectorOutbound
  | UrlTestOutbound;

/** Group outbound payloads (selector / urltest) — never concrete proxy nodes. */
export type GroupOutbound = SelectorOutbound | UrlTestOutbound;

/**
 * Type predicate for group outbounds (selector / urltest).
 *
 * Mirrors Rust `OutboundProtocol::is_group`; used to separate the list into
 * 「分组」/「节点」 sections and to keep group fields out of node forms.
 */
export function isGroupOutbound(protocol: OutboundProtocol): protocol is GroupOutbound {
  return protocol.type === "selector" || protocol.type === "urltest";
}

/**
 * A single custom outbound (`{ id, name, enabled, type, …protocol fields }`).
 *
 * `OutboundProtocol` is flattened into this object in the Rust wire format;
 * the intersection keeps the union discriminated by `type`.
 */
export type CustomOutbound = {
  /** Unique ID (UUID v4 generated by the frontend). */
  id: string;
  /** Display name; also the source of the generated `slice-` tag. */
  name: string;
  enabled: boolean;
} & OutboundProtocol;

/** Custom outbound slice; enabled items are injected, an empty list is a no-op. */
export interface OutboundsSlice {
  items: CustomOutbound[];
}

// ---------------------------------------------------------------------------
// Experimental slice
// ---------------------------------------------------------------------------

/**
 * sing-box `experimental.cache_file` (curated fields).
 *
 * Mirrors Rust `CacheFileSlice` (`experimental.rs`): `enabled` / `path` /
 * `cache_id` / `store_fakeip`. The 1.14-deprecated `store_rdrc` / `rdrc_timeout`
 * are never emitted, and `store_dns` is intentionally out of scope.
 */
export interface CacheFileSlice {
  /** Whether the cache file is enabled. */
  enabled: boolean;
  /** Path to the cache file (empty = sing-box default `cache.db`). */
  path: string;
  /** Identifier for a separate store inside the cache file (empty = none). */
  cache_id: string;
  /** Store fakeip records in the cache file. */
  store_fakeip: boolean;
}

/**
 * Experimental slice: structured form of the sing-box `experimental` section.
 *
 * Only `cache_file` is curated; `clash_api` stays owned by its dedicated
 * mandatory-slice page and `v2ray_api` / `debug` are out of scope.
 */
export interface ExperimentalSlice {
  cache_file: CacheFileSlice;
}

// ---------------------------------------------------------------------------
// Route slice
// ---------------------------------------------------------------------------

/**
 * sing-box `route.default_domain_resolver` (curated fields).
 *
 * Mirrors Rust `DomainResolverSlice` (`route.rs`): the sing-box 1.12+ dial-field
 * object form `{ server, strategy? }`. `client_subnet` is out of scope, and a
 * `null` `strategy` omits the key (follow the global DNS strategy).
 */
export interface DomainResolverSlice {
  /** DNS server tag used to resolve outbound domains. Empty = no override. */
  server: string;
  /** Optional resolution strategy; `null` follows the global DNS strategy. */
  strategy: DnsStrategy | null;
}

/**
 * Route slice: structured form of the sing-box top-level `route` section.
 *
 * Only `final` and `default_domain_resolver` are curated; `rules` / `rule_set` /
 * `auto_detect_interface` stay owned by the template / panel-feature layer.
 */
export interface RouteSlice {
  /** `route.final` override (default outbound tag). Empty = keep `proxy`. */
  final_tag: string;
  /** `route.default_domain_resolver` override. */
  resolver: DomainResolverSlice;
}

// ---------------------------------------------------------------------------
// Container
// ---------------------------------------------------------------------------

/**
 * Config slice container, stored at `data_dir/config_slices.json`.
 *
 * All fields default: an old client without this file loads the default
 * document (empty / no-op slices).
 */
export interface ConfigSlices {
  /** Schema version for future migrations (currently [`SLICE_VERSION`]). */
  version: number;
  dns: DnsSlice;
  outbounds: OutboundsSlice;
  experimental: ExperimentalSlice;
  route: RouteSlice;
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

/** Get the full config slices document. */
export function configSlicesGet(): Promise<ConfigSlices> {
  return invoke<ConfigSlices>("config_slices_get");
}

/** Save the full config slices document (frontend full-patch; validated server-side). */
export function configSlicesSave(input: ConfigSlices): Promise<void> {
  return invoke<void>("config_slices_save", { input });
}

/**
 * Built-in default DNS config as an editable `DnsSlice` (the exact shape the running core
 * uses, computed with the current IPv6 switch). The DNS editor initializes the
 * `follow_system` draft from it, so the built-in defaults are viewable/editable directly and
 * saving a modified body materializes as `takeover` — no manual mode switch needed.
 */
export function builtinDnsSliceGet(): Promise<DnsSlice> {
  return invoke<DnsSlice>("builtin_dns_slice_get");
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build the forced `slice-` tag from a display name (mirrors Rust
 * `outbound_tag`, ADR-0005 §3.1).
 *
 * The name is lower-cased and slugified: unicode alphanumerics are kept, every
 * run of other characters becomes a single `-`, leading/trailing `-` are
 * trimmed. An empty result falls back to `slice-outbound`.
 */
export function outboundTag(name: string): string {
  let slug = "";
  let pendingDash = false;
  for (const ch of name.trim()) {
    if (/[\p{L}\p{N}]/u.test(ch)) {
      if (pendingDash && slug.length > 0) {
        slug += "-";
      }
      pendingDash = false;
      slug += ch.toLowerCase();
    } else {
      pendingDash = true;
    }
  }
  return slug.length === 0 ? "slice-outbound" : `slice-${slug}`;
}

/** Default (empty / no-op slices) config slices, mirroring Rust `ConfigSlices::default`. */
export function defaultConfigSlices(): ConfigSlices {
  return {
    version: SLICE_VERSION,
    dns: {
      mode: "follow_system",
      servers: [],
      rules: [],
      final_tag: "",
      strategy: "prefer_ipv4",
      reverse_mapping: false,
    },
    outbounds: {
      items: [],
    },
    experimental: {
      cache_file: {
        enabled: false,
        path: "",
        cache_id: "",
        store_fakeip: false,
      },
    },
    route: {
      final_tag: "",
      resolver: {
        server: "",
        strategy: null,
      },
    },
  };
}
