[package]
name = "pp-subscription"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tera = { workspace = true }
base64 = { workspace = true }
url = { workspace = true }
pp-common = { workspace = true }
thiserror = { workspace = true }
